AllCops:
  TargetRubyVersion: 2.3
Style/Documentation:
  Enabled: false
Style/AsciiComments :
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'test/*.rb'
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Exclude:
    - 'lib/sunat_invoice/catalogs.rb'
Naming/MemoizedInstanceVariableName:
  Enabled: false
